application:
  # Geometry is a GeoJSON object
  geometry:
    type: Polygon
    coordinates: [[[-180, -84],[180, -84],[180, 84],[-180, 84],[-180, -84]]]
  name: "Land Matrix Knowledge Platform global edition"
  layers:
  - name: "Blue Marble"
    url: "http://cdetux2.unibe.ch/geoserver/lo/wms"
    wms_options:
    - epsg: 900913
    - format: "image/jpeg"
    - layers: "blue_marble"
    - transparent: false
    ol_options:
    - visibility: false
    - isBaseLayer: false
    - sphericalMercator: true
    - maxExtent: [-20037508.34, -20037508.34, 20037508.34, 20037508.34]
    - opacity: 1
  - name: "Accessability"
    url: "http://cdetux2.unibe.ch/geoserver/lo/wms"
    wms_options:
    - epsg: 900913
    - format: "image/jpeg"
    - layers: "accessability"
    - transparent: true
    ol_options:
    - visibility: false
    - isBaseLayer: false
    - sphericalMercator: true
    - maxExtent: [-20037508.34, -20037508.34, 20037508.34, 20037508.34]
    - opacity: 0.7
  - name: "Population Density 2008"
    url: "http://cdetux2.unibe.ch/geoserver/lo/wms"
    wms_options:
    - epsg: 900913
    - format: "image/jpeg"
    - layers: "lspop_2008"
    - transparent: true
    ol_options:
    - visibility: false
    - isBaseLayer: false
    - sphericalMercator: true
    - maxExtent: [-20037508.34, -20037508.34, 20037508.34, 20037508.34]
    - opacity: 0.6
  - name: "Global Land Cover 2009"
    url: "http://cdetux2.unibe.ch/geoserver/lo/wms"
    wms_options:
    - epsg: 900913
    - format: "image/jpeg"
    - layers: "globcover_2009"
    - transparent: true
    ol_options:
    - visibility: false
    - isBaseLayer: false
    - sphericalMercator: true
    - maxExtent: [-20037508.34, -20037508.34, 20037508.34, 20037508.34]
    - opacity: 0.6
  - name: "Global Cropland"
    url: "http://cdetux2.unibe.ch/geoserver/lo/wms"
    wms_options:
    - epsg: 900913
    - format: "image/jpeg"
    - layers: "gl_cropland"
    - transparent: true
    ol_options:
    - visibility: false
    - isBaseLayer: false
    - sphericalMercator: true
    - maxExtent: [-20037508.34, -20037508.34, 20037508.34, 20037508.34]
    - opacity: 0.6
  - name: "Global Pasture Land"
    url: "http://cdetux2.unibe.ch/geoserver/lo/wms"
    wms_options:
    - epsg: 900913
    - format: "image/jpeg"
    - layers: "gl_pasture"
    - transparent: true
    ol_options:
    - visibility: false
    - isBaseLayer: false
    - sphericalMercator: true
    - maxExtent: [-20037508.34, -20037508.34, 20037508.34, 20037508.34]
    - opacity: 0.6
  - name: "Tabi Ocean"
    url: "http://www.tabi.la/geoserver/tabi/wms"
    wms_options:
    - epsg: 900913
    - format: "image/png8"
    - layers: "10m_ocean"
    - transparent: true
    ol_options:
    - visibility: false
    - isBaseLayer: false
    - sphericalMercator: true
    - maxExtent: [-20037508.34, -20037508.34, 20037508.34, 20037508.34]
    - opacity: 0.7
