application:
  # Geometry is a GeoJSON object
  geometry:
    type: Polygon
    coordinates: [[[43.24, -11.95],[50.50, -11.95],[50.50, -25.59],[43.24, -25.59],[43.24, -11.95]]]
  name: "Madagascar"
  layers:
  - name: "Accessability"
    url: "http://cdetux2.unibe.ch/geoserver/lo/wms"
    wms_options:
    - epsg: 900913
    - format: "image/jpeg"
    - layers: "accessability"
    - transparent: true
    ol_options:
    - visibility: false
    - isBaseLayer: false
    - sphericalMercator: true
    - maxExtent: [-20037508.34, -20037508.34, 20037508.34, 20037508.34]
    - opacity: 0.7
  - name: "Population Density 2008"
    url: "http://cdetux2.unibe.ch/geoserver/lo/wms"
    wms_options:
    - epsg: 900913
    - format: "image/jpeg"
    - layers: "lspop_2008"
    - transparent: true
    ol_options:
    - visibility: false
    - isBaseLayer: false
    - sphericalMercator: true
    - maxExtent: [-20037508.34, -20037508.34, 20037508.34, 20037508.34]
    - opacity: 0.6
  - name: "Global Land Cover 2009"
    url: "http://cdetux2.unibe.ch/geoserver/lo/wms"
    wms_options:
    - epsg: 900913
    - format: "image/jpeg"
    - layers: "globcover_2009"
    - transparent: true
    ol_options:
    - visibility: false
    - isBaseLayer: false
    - sphericalMercator: true
    - maxExtent: [-20037508.34, -20037508.34, 20037508.34, 20037508.34]
    - opacity: 0.6
  - name: "Global Cropland"
    url: "http://cdetux2.unibe.ch/geoserver/lo/wms"
    wms_options:
    - epsg: 900913
    - format: "image/jpeg"
    - layers: "gl_cropland"
    - transparent: true
    ol_options:
    - visibility: false
    - isBaseLayer: false
    - sphericalMercator: true
    - maxExtent: [-20037508.34, -20037508.34, 20037508.34, 20037508.34]
    - opacity: 0.6
  - name: "Global Pasture Land"
    url: "http://cdetux2.unibe.ch/geoserver/lo/wms"
    wms_options:
    - epsg: 900913
    - format: "image/jpeg"
    - layers: "gl_pasture"
    - transparent: true
    ol_options:
    - visibility: false
    - isBaseLayer: false
    - sphericalMercator: true
    - maxExtent: [-20037508.34, -20037508.34, 20037508.34, 20037508.34]
    - opacity: 0.6


