application:
  geometry:
    type: Polygon
    coordinates: [[[100.081,13.9099],[107.635,13.9099],[107.635,22.509],[100.081,22.509],[100.081,13.9099]]]
  name: ສາທາລະນະລັດປະຊາທິປະໄຕ ປະຊາຊົນລາວ
  layers:
  - name: "Incidence of Poverty (Lao DECIDE Info)"
    url: "http://www.decide.la/geoserver/wms"
    wms_options:
    - epsg: 900913
    - format: "image/png8"
    - layers: "decide:village-polygon"
    - transparent: true
    - styles: "vrppoac26"
    ol_options:
    - visibility: false
    - isBaseLayer: false
    - sphericalMercator: true
    - maxExtent: [11063487.59, 1543945.80, 12059351.76, 2593727.60]
    - opacity: 0.7
  - name: "Accessibility"
    url: "http://cdetux2.unibe.ch/geoserver/lo/wms"
    wms_options:
    - epsg: 900913
    - format: "image/jpeg"
    - layers: "accessability"
    - transparent: true
    ol_options:
    - visibility: false
    - isBaseLayer: false
    - sphericalMercator: true
    - maxExtent: [-20037508.34, -20037508.34, 20037508.34, 20037508.34]
    - opacity: 0.7
  - name: "Population density (Lao DECIDE Info)"
    url: "http://www.decide.la/geoserver/wms"
    wms_options:
    - epsg: 900913
    - format: "image/png8"
    - layers: "decide:village-polygon"
    - transparent: true
    - styles: "vrpdeaa40"
    ol_options:
    - visibility: false
    - isBaseLayer: false
    - sphericalMercator: true
    - maxExtent: [11063487.59, 1543945.80, 12059351.76, 2593727.60]
    - opacity: 0.7
  - name: "Global Land Cover 2009"
    url: "http://cdetux2.unibe.ch/geoserver/lo/wms"
    wms_options:
    - epsg: 900913
    - format: "image/jpeg"
    - layers: "globcover_2009"
    - transparent: true
    ol_options:
    - visibility: false
    - isBaseLayer: false
    - sphericalMercator: true
    - maxExtent: [-20037508.34, -20037508.34, 20037508.34, 20037508.34]
    - opacity: 0.6
  - name: "Global Cropland"
    url: "http://cdetux2.unibe.ch/geoserver/lo/wms"
    wms_options:
    - epsg: 900913
    - format: "image/jpeg"
    - layers: "gl_cropland"
    - transparent: true
    ol_options:
    - visibility: false
    - isBaseLayer: false
    - sphericalMercator: true
    - maxExtent: [-20037508.34, -20037508.34, 20037508.34, 20037508.34]
    - opacity: 0.6
  - name: "Global Pasture Land"
    url: "http://cdetux2.unibe.ch/geoserver/lo/wms"
    wms_options:
    - epsg: 900913
    - format: "image/jpeg"
    - layers: "gl_pasture"
    - transparent: true
    ol_options:
    - visibility: false
    - isBaseLayer: false
    - sphericalMercator: true
    - maxExtent: [-20037508.34, -20037508.34, 20037508.34, 20037508.34]
    - opacity: 0.6    